# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e6d420a026dbfdc57e9723f4f49b37c3dd5407bea4c059b5a254a52d33ec52aa117861bb524166b0b6b9d50c707c82ccc5f180935c6efdbf8e487e7404d7bdb

test:
  secret_key_base: 719bc84b0301380c53d981c7f375f70119d590fb1f61725c974d5c45d8cbcf1a6cde1f80d568b500a0edcbbdd6059e3e5880bf061615efb24ee541b041ae9f95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
